### ISSUE TITLE
Selecting Solana-devnet, Chiado & eclipse in list of chains crashes the docs page

### ISSUE THREAD

**Issue by brohamgoham** [hyperlane-xyz/v3-docs#123]
Hi 👋Hyperlane team, when selecting certain chains in the docs, the page crashes with `undefined is not an object (evaluating '(f=g).startsWith')`
![IMG_0010](https://github.com/hyperlane-xyz/v3-docs/assets/80609236/f2d4350c-8e44-4ee2-88e0-0cf244731d70)
![IMG_0011](https://github.com/hyperlane-xyz/v3-docs/assets/80609236/c9c56854-ef8c-4fd5-b5f2-ecfa1efc0d68)

**Comment by avious00** [comment]
thanks for reporting this issue! will put up a fix in https://github.com/hyperlane-xyz/v3-docs/issues/174
