### ISSUE TITLE
docker-compose step-by-step guide

### ISSUE THREAD

**Issue by avious00** [hyperlane-xyz/v3-docs#142]
Review https://github.com/EigenYields/v3-docs/pull/1

**Comment by avious00** [comment]
claimed by 0xHmm from EigenYields https://github.com/EigenYields/v3-docs/pull/1

**Comment by EigenYields** [comment]
added pr for this #144

**Comment by avious00** [comment]
hey @EigenYields thanks for your helpful contribution! reaching out in DMs

**Comment by avious00** [comment]
https://github.com/hyperlane-xyz/v3-docs/pull/157
