### ISSUE TITLE
Restrict `Send your first message` addresses to Ethereum

### ISSUE THREAD

**Issue by avious00** [hyperlane-xyz/v3-docs#174]
Send your first message page crashes when selecting any Solana testnet chain + Chiado, as reported by https://github.com/hyperlane-xyz/v3-docs/issues/123 and a partner

Test that chains work + chain selection a) does not crash the docs b) the send message commands work, then add https://docs.hyperlane.xyz/docs/your-first-message back in sidebar.js (currently commented out)

**Comment by avious00** [comment]
@jmrossy may have addressed this in https://github.com/hyperlane-xyz/v3-docs/commit/b0ec7b414b74054e3870282c7c5dea77b618c2fa

**Comment by avious00** [comment]
Successfully sent message from Sepolia to Basesepolia but running into errors on other pairs

<img width="809" alt="Screenshot 2024-09-18 at 2 42 54 PM" src="https://github.com/user-attachments/assets/5c3b024a-8497-43c9-b4cf-da46e20b1dac">
<img width="827" alt="Screenshot 2024-09-18 at 2 42 45 PM" src="https://github.com/user-attachments/assets/84a8270a-acc6-479c-aedf-ca8dbe66c1f9">

**Comment by paulbalaji** [comment]
I think this issue is related to https://github.com/hyperlane-xyz/issues/issues/1374, hope to resolve before the next testnet batch

**Comment by avious00** [comment]
@paulbalaji could you also own this ticket making sure this works end to end (not crashing, send a message command works)? @yorhodes mentioned it being helpful for a getting started experience and missing for the hackathon
