### ISSUE TITLE
Clarify how to configure IGP

### ISSUE THREAD

**Issue by avious00** [hyperlane-xyz/v3-docs#51]
### Need
Clarify and improve the ease of understanding on how to set IGP static config of overhead, oracles, and the metadata config of gas limit. We should also update this to explain the concept of "system overhead" vs "handle gas limit"

#### Relevant Page
[IGP Hooks](https://docs.hyperlane.xyz/docs/reference/hooks/interchain-gas)

#### Submitted By
Thank you to @NicholasDotSol from [Neutron](https://github.com/neutron-org/neutron)

**Comment by avious00** [comment]
from Nam: "we need to clarify that the IGP depending on the destination chain sets a gasOverhead"

**Comment by nambrot** [comment]
Just to clarify, I would interpret this ticket to be adding this to the reference or protocol section as to how the contract/concept works, not how to use our current tooling as to how to do that, @yorhodes does that match your view?
