### ISSUE TITLE
Revamp docs sidebar

### ISSUE THREAD

**Issue by avious00** [hyperlane-xyz/v3-docs#67]
[Discord convo](https://discord.com/channels/935678348330434570/1068248896809222237/1215681576885551104) for context

Add'l feedback from Noah on [Reference/Protocol](https://discord.com/channels/935678348330434570/935678739663192184/1222973352222658631)

**Comment by edakturk14** [comment]
Closing this issue as we've update the sidebar and the ref/protocol section
